'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.Service1Soap")>  _
    Public Interface Service1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/login", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function login(ByVal odano As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/asd", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function asd(ByVal odano As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/calistir", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub calistir(ByVal sql As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/sipariskayit", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sipariskayit(ByVal odano As String, ByVal yemekadi As String, ByVal yemekadet As String, ByVal yemekfiyat As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemekhanesil", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemekhanesil(ByVal id As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/servissil", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function servissil(ByVal id As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/servisekle", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function servisekle(ByVal odano As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemekgosterid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemekgosterid() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemekgosterisim", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemekgosterisim() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemekgosterresim", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemekgosterresim() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/vericekme", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function vericekme(ByVal sql As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemeklerigosterid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemeklerigosterid(ByVal menuidsi As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemeklerigosterisim", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemeklerigosterisim(ByVal menuidsi As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemeklerigosterfiyat", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemeklerigosterfiyat(ByVal menuidsi As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemeklerigosterresim", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemeklerigosterresim(ByVal menuidsi As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemekhaneodano", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemekhaneodano() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemekhaneyemekid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemekhaneyemekid() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemekhaneyemekadi", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemekhaneyemekadi() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/yemekhaneyemekadet", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function yemekhaneyemekadet() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/serviselamanid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function serviselamanid() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/serviselamanoda", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function serviselamanoda() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/kullaniciid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function kullaniciid() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/kullaniciadi", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function kullaniciadi() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/galeriid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function galeriid() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/galeriodano", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function galeriodano() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/galeriresim", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function galeriresim() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/aktivite_id", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function aktivite_id() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/aktivite_yazi", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function aktivite_yazi() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/aktivite_resim", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function aktivite_resim() As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Service1SoapChannel
        Inherits ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.Service1Soap)
        Implements ServiceReference1.Service1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements ServiceReference1.Service1Soap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        Public Function login(ByVal odano As String) As String Implements ServiceReference1.Service1Soap.login
            Return MyBase.Channel.login(odano)
        End Function
        
        Public Function asd(ByVal odano As String) As System.Data.DataSet Implements ServiceReference1.Service1Soap.asd
            Return MyBase.Channel.asd(odano)
        End Function
        
        Public Sub calistir(ByVal sql As String) Implements ServiceReference1.Service1Soap.calistir
            MyBase.Channel.calistir(sql)
        End Sub
        
        Public Function sipariskayit(ByVal odano As String, ByVal yemekadi As String, ByVal yemekadet As String, ByVal yemekfiyat As String) As Object Implements ServiceReference1.Service1Soap.sipariskayit
            Return MyBase.Channel.sipariskayit(odano, yemekadi, yemekadet, yemekfiyat)
        End Function
        
        Public Function yemekhanesil(ByVal id As String) As Object Implements ServiceReference1.Service1Soap.yemekhanesil
            Return MyBase.Channel.yemekhanesil(id)
        End Function
        
        Public Function servissil(ByVal id As String) As Object Implements ServiceReference1.Service1Soap.servissil
            Return MyBase.Channel.servissil(id)
        End Function
        
        Public Function servisekle(ByVal odano As String) As Object Implements ServiceReference1.Service1Soap.servisekle
            Return MyBase.Channel.servisekle(odano)
        End Function
        
        Public Function yemekgosterid() As String Implements ServiceReference1.Service1Soap.yemekgosterid
            Return MyBase.Channel.yemekgosterid
        End Function
        
        Public Function yemekgosterisim() As String Implements ServiceReference1.Service1Soap.yemekgosterisim
            Return MyBase.Channel.yemekgosterisim
        End Function
        
        Public Function yemekgosterresim() As String Implements ServiceReference1.Service1Soap.yemekgosterresim
            Return MyBase.Channel.yemekgosterresim
        End Function
        
        Public Function vericekme(ByVal sql As String) As System.Data.DataSet Implements ServiceReference1.Service1Soap.vericekme
            Return MyBase.Channel.vericekme(sql)
        End Function
        
        Public Function yemeklerigosterid(ByVal menuidsi As Integer) As String Implements ServiceReference1.Service1Soap.yemeklerigosterid
            Return MyBase.Channel.yemeklerigosterid(menuidsi)
        End Function
        
        Public Function yemeklerigosterisim(ByVal menuidsi As Integer) As String Implements ServiceReference1.Service1Soap.yemeklerigosterisim
            Return MyBase.Channel.yemeklerigosterisim(menuidsi)
        End Function
        
        Public Function yemeklerigosterfiyat(ByVal menuidsi As Integer) As String Implements ServiceReference1.Service1Soap.yemeklerigosterfiyat
            Return MyBase.Channel.yemeklerigosterfiyat(menuidsi)
        End Function
        
        Public Function yemeklerigosterresim(ByVal menuidsi As Integer) As String Implements ServiceReference1.Service1Soap.yemeklerigosterresim
            Return MyBase.Channel.yemeklerigosterresim(menuidsi)
        End Function
        
        Public Function yemekhaneodano() As String Implements ServiceReference1.Service1Soap.yemekhaneodano
            Return MyBase.Channel.yemekhaneodano
        End Function
        
        Public Function yemekhaneyemekid() As String Implements ServiceReference1.Service1Soap.yemekhaneyemekid
            Return MyBase.Channel.yemekhaneyemekid
        End Function
        
        Public Function yemekhaneyemekadi() As String Implements ServiceReference1.Service1Soap.yemekhaneyemekadi
            Return MyBase.Channel.yemekhaneyemekadi
        End Function
        
        Public Function yemekhaneyemekadet() As String Implements ServiceReference1.Service1Soap.yemekhaneyemekadet
            Return MyBase.Channel.yemekhaneyemekadet
        End Function
        
        Public Function serviselamanid() As String Implements ServiceReference1.Service1Soap.serviselamanid
            Return MyBase.Channel.serviselamanid
        End Function
        
        Public Function serviselamanoda() As String Implements ServiceReference1.Service1Soap.serviselamanoda
            Return MyBase.Channel.serviselamanoda
        End Function
        
        Public Function kullaniciid() As String Implements ServiceReference1.Service1Soap.kullaniciid
            Return MyBase.Channel.kullaniciid
        End Function
        
        Public Function kullaniciadi() As String Implements ServiceReference1.Service1Soap.kullaniciadi
            Return MyBase.Channel.kullaniciadi
        End Function
        
        Public Function galeriid() As String Implements ServiceReference1.Service1Soap.galeriid
            Return MyBase.Channel.galeriid
        End Function
        
        Public Function galeriodano() As String Implements ServiceReference1.Service1Soap.galeriodano
            Return MyBase.Channel.galeriodano
        End Function
        
        Public Function galeriresim() As String Implements ServiceReference1.Service1Soap.galeriresim
            Return MyBase.Channel.galeriresim
        End Function
        
        Public Function aktivite_id() As String Implements ServiceReference1.Service1Soap.aktivite_id
            Return MyBase.Channel.aktivite_id
        End Function
        
        Public Function aktivite_yazi() As String Implements ServiceReference1.Service1Soap.aktivite_yazi
            Return MyBase.Channel.aktivite_yazi
        End Function
        
        Public Function aktivite_resim() As String Implements ServiceReference1.Service1Soap.aktivite_resim
            Return MyBase.Channel.aktivite_resim
        End Function
    End Class
End Namespace
