// <auto-generated />
namespace Calisma_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class calismadb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(calismadb));
        
        string IMigrationMetadata.Id
        {
            get { return "201510302122597_calismadb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
