'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace com.otelservisi.www
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private loginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private asdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private calistirOperationCompleted As System.Threading.SendOrPostCallback
        
        Private sipariskayitOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemekhanesilOperationCompleted As System.Threading.SendOrPostCallback
        
        Private servissilOperationCompleted As System.Threading.SendOrPostCallback
        
        Private servisekleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemekgosteridOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemekgosterisimOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemekgosterresimOperationCompleted As System.Threading.SendOrPostCallback
        
        Private vericekmeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemeklerigosteridOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemeklerigosterisimOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemeklerigosterfiyatOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemeklerigosterresimOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemekhaneodanoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemekhaneyemekidOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemekhaneyemekadiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private yemekhaneyemekadetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private serviselamanidOperationCompleted As System.Threading.SendOrPostCallback
        
        Private serviselamanodaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private kullaniciidOperationCompleted As System.Threading.SendOrPostCallback
        
        Private kullaniciadiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.otel_proje.My.MySettings.Default.otel_proje_com_otelservisi_www_Service1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event loginCompleted As loginCompletedEventHandler
        
        '''<remarks/>
        Public Event asdCompleted As asdCompletedEventHandler
        
        '''<remarks/>
        Public Event calistirCompleted As calistirCompletedEventHandler
        
        '''<remarks/>
        Public Event sipariskayitCompleted As sipariskayitCompletedEventHandler
        
        '''<remarks/>
        Public Event yemekhanesilCompleted As yemekhanesilCompletedEventHandler
        
        '''<remarks/>
        Public Event servissilCompleted As servissilCompletedEventHandler
        
        '''<remarks/>
        Public Event servisekleCompleted As servisekleCompletedEventHandler
        
        '''<remarks/>
        Public Event yemekgosteridCompleted As yemekgosteridCompletedEventHandler
        
        '''<remarks/>
        Public Event yemekgosterisimCompleted As yemekgosterisimCompletedEventHandler
        
        '''<remarks/>
        Public Event yemekgosterresimCompleted As yemekgosterresimCompletedEventHandler
        
        '''<remarks/>
        Public Event vericekmeCompleted As vericekmeCompletedEventHandler
        
        '''<remarks/>
        Public Event yemeklerigosteridCompleted As yemeklerigosteridCompletedEventHandler
        
        '''<remarks/>
        Public Event yemeklerigosterisimCompleted As yemeklerigosterisimCompletedEventHandler
        
        '''<remarks/>
        Public Event yemeklerigosterfiyatCompleted As yemeklerigosterfiyatCompletedEventHandler
        
        '''<remarks/>
        Public Event yemeklerigosterresimCompleted As yemeklerigosterresimCompletedEventHandler
        
        '''<remarks/>
        Public Event yemekhaneodanoCompleted As yemekhaneodanoCompletedEventHandler
        
        '''<remarks/>
        Public Event yemekhaneyemekidCompleted As yemekhaneyemekidCompletedEventHandler
        
        '''<remarks/>
        Public Event yemekhaneyemekadiCompleted As yemekhaneyemekadiCompletedEventHandler
        
        '''<remarks/>
        Public Event yemekhaneyemekadetCompleted As yemekhaneyemekadetCompletedEventHandler
        
        '''<remarks/>
        Public Event serviselamanidCompleted As serviselamanidCompletedEventHandler
        
        '''<remarks/>
        Public Event serviselamanodaCompleted As serviselamanodaCompletedEventHandler
        
        '''<remarks/>
        Public Event kullaniciidCompleted As kullaniciidCompletedEventHandler
        
        '''<remarks/>
        Public Event kullaniciadiCompleted As kullaniciadiCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync()
            Me.HelloWorldAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function login(ByVal odano As String) As String
            Dim results() As Object = Me.Invoke("login", New Object() {odano})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub loginAsync(ByVal odano As String)
            Me.loginAsync(odano, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub loginAsync(ByVal odano As String, ByVal userState As Object)
            If (Me.loginOperationCompleted Is Nothing) Then
                Me.loginOperationCompleted = AddressOf Me.OnloginOperationCompleted
            End If
            Me.InvokeAsync("login", New Object() {odano}, Me.loginOperationCompleted, userState)
        End Sub
        
        Private Sub OnloginOperationCompleted(ByVal arg As Object)
            If (Not (Me.loginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent loginCompleted(Me, New loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/asd", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function asd(ByVal odano As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("asd", New Object() {odano})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub asdAsync(ByVal odano As String)
            Me.asdAsync(odano, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub asdAsync(ByVal odano As String, ByVal userState As Object)
            If (Me.asdOperationCompleted Is Nothing) Then
                Me.asdOperationCompleted = AddressOf Me.OnasdOperationCompleted
            End If
            Me.InvokeAsync("asd", New Object() {odano}, Me.asdOperationCompleted, userState)
        End Sub
        
        Private Sub OnasdOperationCompleted(ByVal arg As Object)
            If (Not (Me.asdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent asdCompleted(Me, New asdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calistir", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub calistir(ByVal sql As String)
            Me.Invoke("calistir", New Object() {sql})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub calistirAsync(ByVal sql As String)
            Me.calistirAsync(sql, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub calistirAsync(ByVal sql As String, ByVal userState As Object)
            If (Me.calistirOperationCompleted Is Nothing) Then
                Me.calistirOperationCompleted = AddressOf Me.OncalistirOperationCompleted
            End If
            Me.InvokeAsync("calistir", New Object() {sql}, Me.calistirOperationCompleted, userState)
        End Sub
        
        Private Sub OncalistirOperationCompleted(ByVal arg As Object)
            If (Not (Me.calistirCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent calistirCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sipariskayit", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function sipariskayit(ByVal odano As String, ByVal yemekadi As String, ByVal yemekadet As String, ByVal yemekfiyat As String) As Object
            Dim results() As Object = Me.Invoke("sipariskayit", New Object() {odano, yemekadi, yemekadet, yemekfiyat})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub sipariskayitAsync(ByVal odano As String, ByVal yemekadi As String, ByVal yemekadet As String, ByVal yemekfiyat As String)
            Me.sipariskayitAsync(odano, yemekadi, yemekadet, yemekfiyat, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub sipariskayitAsync(ByVal odano As String, ByVal yemekadi As String, ByVal yemekadet As String, ByVal yemekfiyat As String, ByVal userState As Object)
            If (Me.sipariskayitOperationCompleted Is Nothing) Then
                Me.sipariskayitOperationCompleted = AddressOf Me.OnsipariskayitOperationCompleted
            End If
            Me.InvokeAsync("sipariskayit", New Object() {odano, yemekadi, yemekadet, yemekfiyat}, Me.sipariskayitOperationCompleted, userState)
        End Sub
        
        Private Sub OnsipariskayitOperationCompleted(ByVal arg As Object)
            If (Not (Me.sipariskayitCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent sipariskayitCompleted(Me, New sipariskayitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemekhanesil", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemekhanesil(ByVal id As String) As Object
            Dim results() As Object = Me.Invoke("yemekhanesil", New Object() {id})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemekhanesilAsync(ByVal id As String)
            Me.yemekhanesilAsync(id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemekhanesilAsync(ByVal id As String, ByVal userState As Object)
            If (Me.yemekhanesilOperationCompleted Is Nothing) Then
                Me.yemekhanesilOperationCompleted = AddressOf Me.OnyemekhanesilOperationCompleted
            End If
            Me.InvokeAsync("yemekhanesil", New Object() {id}, Me.yemekhanesilOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemekhanesilOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemekhanesilCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemekhanesilCompleted(Me, New yemekhanesilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/servissil", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function servissil(ByVal id As String) As Object
            Dim results() As Object = Me.Invoke("servissil", New Object() {id})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub servissilAsync(ByVal id As String)
            Me.servissilAsync(id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub servissilAsync(ByVal id As String, ByVal userState As Object)
            If (Me.servissilOperationCompleted Is Nothing) Then
                Me.servissilOperationCompleted = AddressOf Me.OnservissilOperationCompleted
            End If
            Me.InvokeAsync("servissil", New Object() {id}, Me.servissilOperationCompleted, userState)
        End Sub
        
        Private Sub OnservissilOperationCompleted(ByVal arg As Object)
            If (Not (Me.servissilCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent servissilCompleted(Me, New servissilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/servisekle", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function servisekle(ByVal odano As String) As Object
            Dim results() As Object = Me.Invoke("servisekle", New Object() {odano})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub servisekleAsync(ByVal odano As String)
            Me.servisekleAsync(odano, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub servisekleAsync(ByVal odano As String, ByVal userState As Object)
            If (Me.servisekleOperationCompleted Is Nothing) Then
                Me.servisekleOperationCompleted = AddressOf Me.OnservisekleOperationCompleted
            End If
            Me.InvokeAsync("servisekle", New Object() {odano}, Me.servisekleOperationCompleted, userState)
        End Sub
        
        Private Sub OnservisekleOperationCompleted(ByVal arg As Object)
            If (Not (Me.servisekleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent servisekleCompleted(Me, New servisekleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemekgosterid", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemekgosterid() As String
            Dim results() As Object = Me.Invoke("yemekgosterid", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemekgosteridAsync()
            Me.yemekgosteridAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemekgosteridAsync(ByVal userState As Object)
            If (Me.yemekgosteridOperationCompleted Is Nothing) Then
                Me.yemekgosteridOperationCompleted = AddressOf Me.OnyemekgosteridOperationCompleted
            End If
            Me.InvokeAsync("yemekgosterid", New Object(-1) {}, Me.yemekgosteridOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemekgosteridOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemekgosteridCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemekgosteridCompleted(Me, New yemekgosteridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemekgosterisim", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemekgosterisim() As String
            Dim results() As Object = Me.Invoke("yemekgosterisim", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemekgosterisimAsync()
            Me.yemekgosterisimAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemekgosterisimAsync(ByVal userState As Object)
            If (Me.yemekgosterisimOperationCompleted Is Nothing) Then
                Me.yemekgosterisimOperationCompleted = AddressOf Me.OnyemekgosterisimOperationCompleted
            End If
            Me.InvokeAsync("yemekgosterisim", New Object(-1) {}, Me.yemekgosterisimOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemekgosterisimOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemekgosterisimCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemekgosterisimCompleted(Me, New yemekgosterisimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemekgosterresim", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemekgosterresim() As String
            Dim results() As Object = Me.Invoke("yemekgosterresim", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemekgosterresimAsync()
            Me.yemekgosterresimAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemekgosterresimAsync(ByVal userState As Object)
            If (Me.yemekgosterresimOperationCompleted Is Nothing) Then
                Me.yemekgosterresimOperationCompleted = AddressOf Me.OnyemekgosterresimOperationCompleted
            End If
            Me.InvokeAsync("yemekgosterresim", New Object(-1) {}, Me.yemekgosterresimOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemekgosterresimOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemekgosterresimCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemekgosterresimCompleted(Me, New yemekgosterresimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vericekme", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function vericekme(ByVal sql As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("vericekme", New Object() {sql})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub vericekmeAsync(ByVal sql As String)
            Me.vericekmeAsync(sql, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub vericekmeAsync(ByVal sql As String, ByVal userState As Object)
            If (Me.vericekmeOperationCompleted Is Nothing) Then
                Me.vericekmeOperationCompleted = AddressOf Me.OnvericekmeOperationCompleted
            End If
            Me.InvokeAsync("vericekme", New Object() {sql}, Me.vericekmeOperationCompleted, userState)
        End Sub
        
        Private Sub OnvericekmeOperationCompleted(ByVal arg As Object)
            If (Not (Me.vericekmeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent vericekmeCompleted(Me, New vericekmeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemeklerigosterid", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemeklerigosterid(ByVal menuidsi As Integer) As String
            Dim results() As Object = Me.Invoke("yemeklerigosterid", New Object() {menuidsi})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemeklerigosteridAsync(ByVal menuidsi As Integer)
            Me.yemeklerigosteridAsync(menuidsi, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemeklerigosteridAsync(ByVal menuidsi As Integer, ByVal userState As Object)
            If (Me.yemeklerigosteridOperationCompleted Is Nothing) Then
                Me.yemeklerigosteridOperationCompleted = AddressOf Me.OnyemeklerigosteridOperationCompleted
            End If
            Me.InvokeAsync("yemeklerigosterid", New Object() {menuidsi}, Me.yemeklerigosteridOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemeklerigosteridOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemeklerigosteridCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemeklerigosteridCompleted(Me, New yemeklerigosteridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemeklerigosterisim", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemeklerigosterisim(ByVal menuidsi As Integer) As String
            Dim results() As Object = Me.Invoke("yemeklerigosterisim", New Object() {menuidsi})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemeklerigosterisimAsync(ByVal menuidsi As Integer)
            Me.yemeklerigosterisimAsync(menuidsi, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemeklerigosterisimAsync(ByVal menuidsi As Integer, ByVal userState As Object)
            If (Me.yemeklerigosterisimOperationCompleted Is Nothing) Then
                Me.yemeklerigosterisimOperationCompleted = AddressOf Me.OnyemeklerigosterisimOperationCompleted
            End If
            Me.InvokeAsync("yemeklerigosterisim", New Object() {menuidsi}, Me.yemeklerigosterisimOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemeklerigosterisimOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemeklerigosterisimCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemeklerigosterisimCompleted(Me, New yemeklerigosterisimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemeklerigosterfiyat", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemeklerigosterfiyat(ByVal menuidsi As Integer) As String
            Dim results() As Object = Me.Invoke("yemeklerigosterfiyat", New Object() {menuidsi})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemeklerigosterfiyatAsync(ByVal menuidsi As Integer)
            Me.yemeklerigosterfiyatAsync(menuidsi, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemeklerigosterfiyatAsync(ByVal menuidsi As Integer, ByVal userState As Object)
            If (Me.yemeklerigosterfiyatOperationCompleted Is Nothing) Then
                Me.yemeklerigosterfiyatOperationCompleted = AddressOf Me.OnyemeklerigosterfiyatOperationCompleted
            End If
            Me.InvokeAsync("yemeklerigosterfiyat", New Object() {menuidsi}, Me.yemeklerigosterfiyatOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemeklerigosterfiyatOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemeklerigosterfiyatCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemeklerigosterfiyatCompleted(Me, New yemeklerigosterfiyatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemeklerigosterresim", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemeklerigosterresim(ByVal menuidsi As Integer) As String
            Dim results() As Object = Me.Invoke("yemeklerigosterresim", New Object() {menuidsi})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemeklerigosterresimAsync(ByVal menuidsi As Integer)
            Me.yemeklerigosterresimAsync(menuidsi, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemeklerigosterresimAsync(ByVal menuidsi As Integer, ByVal userState As Object)
            If (Me.yemeklerigosterresimOperationCompleted Is Nothing) Then
                Me.yemeklerigosterresimOperationCompleted = AddressOf Me.OnyemeklerigosterresimOperationCompleted
            End If
            Me.InvokeAsync("yemeklerigosterresim", New Object() {menuidsi}, Me.yemeklerigosterresimOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemeklerigosterresimOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemeklerigosterresimCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemeklerigosterresimCompleted(Me, New yemeklerigosterresimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemekhaneodano", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemekhaneodano() As String
            Dim results() As Object = Me.Invoke("yemekhaneodano", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemekhaneodanoAsync()
            Me.yemekhaneodanoAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemekhaneodanoAsync(ByVal userState As Object)
            If (Me.yemekhaneodanoOperationCompleted Is Nothing) Then
                Me.yemekhaneodanoOperationCompleted = AddressOf Me.OnyemekhaneodanoOperationCompleted
            End If
            Me.InvokeAsync("yemekhaneodano", New Object(-1) {}, Me.yemekhaneodanoOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemekhaneodanoOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemekhaneodanoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemekhaneodanoCompleted(Me, New yemekhaneodanoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemekhaneyemekid", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemekhaneyemekid() As String
            Dim results() As Object = Me.Invoke("yemekhaneyemekid", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemekhaneyemekidAsync()
            Me.yemekhaneyemekidAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemekhaneyemekidAsync(ByVal userState As Object)
            If (Me.yemekhaneyemekidOperationCompleted Is Nothing) Then
                Me.yemekhaneyemekidOperationCompleted = AddressOf Me.OnyemekhaneyemekidOperationCompleted
            End If
            Me.InvokeAsync("yemekhaneyemekid", New Object(-1) {}, Me.yemekhaneyemekidOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemekhaneyemekidOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemekhaneyemekidCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemekhaneyemekidCompleted(Me, New yemekhaneyemekidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemekhaneyemekadi", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemekhaneyemekadi() As String
            Dim results() As Object = Me.Invoke("yemekhaneyemekadi", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemekhaneyemekadiAsync()
            Me.yemekhaneyemekadiAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemekhaneyemekadiAsync(ByVal userState As Object)
            If (Me.yemekhaneyemekadiOperationCompleted Is Nothing) Then
                Me.yemekhaneyemekadiOperationCompleted = AddressOf Me.OnyemekhaneyemekadiOperationCompleted
            End If
            Me.InvokeAsync("yemekhaneyemekadi", New Object(-1) {}, Me.yemekhaneyemekadiOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemekhaneyemekadiOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemekhaneyemekadiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemekhaneyemekadiCompleted(Me, New yemekhaneyemekadiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yemekhaneyemekadet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function yemekhaneyemekadet() As String
            Dim results() As Object = Me.Invoke("yemekhaneyemekadet", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub yemekhaneyemekadetAsync()
            Me.yemekhaneyemekadetAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub yemekhaneyemekadetAsync(ByVal userState As Object)
            If (Me.yemekhaneyemekadetOperationCompleted Is Nothing) Then
                Me.yemekhaneyemekadetOperationCompleted = AddressOf Me.OnyemekhaneyemekadetOperationCompleted
            End If
            Me.InvokeAsync("yemekhaneyemekadet", New Object(-1) {}, Me.yemekhaneyemekadetOperationCompleted, userState)
        End Sub
        
        Private Sub OnyemekhaneyemekadetOperationCompleted(ByVal arg As Object)
            If (Not (Me.yemekhaneyemekadetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent yemekhaneyemekadetCompleted(Me, New yemekhaneyemekadetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/serviselamanid", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function serviselamanid() As String
            Dim results() As Object = Me.Invoke("serviselamanid", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub serviselamanidAsync()
            Me.serviselamanidAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub serviselamanidAsync(ByVal userState As Object)
            If (Me.serviselamanidOperationCompleted Is Nothing) Then
                Me.serviselamanidOperationCompleted = AddressOf Me.OnserviselamanidOperationCompleted
            End If
            Me.InvokeAsync("serviselamanid", New Object(-1) {}, Me.serviselamanidOperationCompleted, userState)
        End Sub
        
        Private Sub OnserviselamanidOperationCompleted(ByVal arg As Object)
            If (Not (Me.serviselamanidCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent serviselamanidCompleted(Me, New serviselamanidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/serviselamanoda", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function serviselamanoda() As String
            Dim results() As Object = Me.Invoke("serviselamanoda", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub serviselamanodaAsync()
            Me.serviselamanodaAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub serviselamanodaAsync(ByVal userState As Object)
            If (Me.serviselamanodaOperationCompleted Is Nothing) Then
                Me.serviselamanodaOperationCompleted = AddressOf Me.OnserviselamanodaOperationCompleted
            End If
            Me.InvokeAsync("serviselamanoda", New Object(-1) {}, Me.serviselamanodaOperationCompleted, userState)
        End Sub
        
        Private Sub OnserviselamanodaOperationCompleted(ByVal arg As Object)
            If (Not (Me.serviselamanodaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent serviselamanodaCompleted(Me, New serviselamanodaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/kullaniciid", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function kullaniciid() As String
            Dim results() As Object = Me.Invoke("kullaniciid", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kullaniciidAsync()
            Me.kullaniciidAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kullaniciidAsync(ByVal userState As Object)
            If (Me.kullaniciidOperationCompleted Is Nothing) Then
                Me.kullaniciidOperationCompleted = AddressOf Me.OnkullaniciidOperationCompleted
            End If
            Me.InvokeAsync("kullaniciid", New Object(-1) {}, Me.kullaniciidOperationCompleted, userState)
        End Sub
        
        Private Sub OnkullaniciidOperationCompleted(ByVal arg As Object)
            If (Not (Me.kullaniciidCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kullaniciidCompleted(Me, New kullaniciidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/kullaniciadi", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function kullaniciadi() As String
            Dim results() As Object = Me.Invoke("kullaniciadi", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kullaniciadiAsync()
            Me.kullaniciadiAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kullaniciadiAsync(ByVal userState As Object)
            If (Me.kullaniciadiOperationCompleted Is Nothing) Then
                Me.kullaniciadiOperationCompleted = AddressOf Me.OnkullaniciadiOperationCompleted
            End If
            Me.InvokeAsync("kullaniciadi", New Object(-1) {}, Me.kullaniciadiOperationCompleted, userState)
        End Sub
        
        Private Sub OnkullaniciadiOperationCompleted(ByVal arg As Object)
            If (Not (Me.kullaniciadiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kullaniciadiCompleted(Me, New kullaniciadiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub loginCompletedEventHandler(ByVal sender As Object, ByVal e As loginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class loginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub asdCompletedEventHandler(ByVal sender As Object, ByVal e As asdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class asdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub calistirCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub sipariskayitCompletedEventHandler(ByVal sender As Object, ByVal e As sipariskayitCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class sipariskayitCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemekhanesilCompletedEventHandler(ByVal sender As Object, ByVal e As yemekhanesilCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemekhanesilCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub servissilCompletedEventHandler(ByVal sender As Object, ByVal e As servissilCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class servissilCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub servisekleCompletedEventHandler(ByVal sender As Object, ByVal e As servisekleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class servisekleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemekgosteridCompletedEventHandler(ByVal sender As Object, ByVal e As yemekgosteridCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemekgosteridCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemekgosterisimCompletedEventHandler(ByVal sender As Object, ByVal e As yemekgosterisimCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemekgosterisimCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemekgosterresimCompletedEventHandler(ByVal sender As Object, ByVal e As yemekgosterresimCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemekgosterresimCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub vericekmeCompletedEventHandler(ByVal sender As Object, ByVal e As vericekmeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class vericekmeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemeklerigosteridCompletedEventHandler(ByVal sender As Object, ByVal e As yemeklerigosteridCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemeklerigosteridCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemeklerigosterisimCompletedEventHandler(ByVal sender As Object, ByVal e As yemeklerigosterisimCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemeklerigosterisimCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemeklerigosterfiyatCompletedEventHandler(ByVal sender As Object, ByVal e As yemeklerigosterfiyatCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemeklerigosterfiyatCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemeklerigosterresimCompletedEventHandler(ByVal sender As Object, ByVal e As yemeklerigosterresimCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemeklerigosterresimCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemekhaneodanoCompletedEventHandler(ByVal sender As Object, ByVal e As yemekhaneodanoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemekhaneodanoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemekhaneyemekidCompletedEventHandler(ByVal sender As Object, ByVal e As yemekhaneyemekidCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemekhaneyemekidCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemekhaneyemekadiCompletedEventHandler(ByVal sender As Object, ByVal e As yemekhaneyemekadiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemekhaneyemekadiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub yemekhaneyemekadetCompletedEventHandler(ByVal sender As Object, ByVal e As yemekhaneyemekadetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class yemekhaneyemekadetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub serviselamanidCompletedEventHandler(ByVal sender As Object, ByVal e As serviselamanidCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class serviselamanidCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub serviselamanodaCompletedEventHandler(ByVal sender As Object, ByVal e As serviselamanodaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class serviselamanodaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub kullaniciidCompletedEventHandler(ByVal sender As Object, ByVal e As kullaniciidCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class kullaniciidCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub kullaniciadiCompletedEventHandler(ByVal sender As Object, ByVal e As kullaniciadiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class kullaniciadiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
